version: '3.7'
services:

  terraform:
    image: hashicorp/terraform:1.1.7
    volumes:
      - '.:/app'
    working_dir: '/app'

  terraform-docs:
    image: cytopia/terraform-docs
    volumes:
      - '.:/app'
    working_dir: '/app'
